name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # important: run everything inside frontend folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}     # add this in GitHub repo secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}   # from your Vercel settings
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # from your Vercel settings
          working-directory: ./frontend
          scope: ${{ secrets.VERCEL_SCOPE }}  # optional, if you’re in a Vercel team
          